on:
  push:
    branches:
      - main
  workflow_dispatch:
      
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@4.0.0
        with:
          args: "package"
      - name: upload VSIX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./markdownsnippetinclude-1.0.0.vsix
          asset_name: markdownsnippetinclude-1.0.0.vsix
          asset_content_type: application/xml
